version: '3.8'

volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data

networks:
  prom-graf:
    name: prom-graf
  inception:
    external: true

services:
  # prometheus
  prometheus:
    image: prometheus
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - prometheus_data:/var/lib/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/web-config.yml:/etc/prometheus/web-config.yml
      - ./prometheus/config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - inception
      - prom-graf

  # grafana
  grafana:
    image: grafana
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - inception
      - prom-graf

  # mysqld exporter for MariaDB
  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    command:
      - --config.my-cnf=/etc/.my.cnf
      - --mysqld.address=mariadb:3306
    volumes:
      - ./.my.cnf:/etc/.my.cnf
    networks:
      - inception
      - prom-graf

  # nginx exporter for Nginx
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: -nginx.scrape-uri https://nginx:443/nginx_status
    networks:
      - inception
      - prom-graf

  # php-fpm exporter for WordPress
  php_fpm_exporter:
    image: hipages/php-fpm_exporter
    container_name: php_fpm_exporter
    environment:
      FPM_SCRAPE_URI: tcp://wordpress:9000/status
    networks:
      - inception
      - prom-graf