global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - localhost:9090
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: "inception"
    static_configs:
      - targets:
        - mysqld_exporter:9104
        - nginx_exporter:9113
        - php_fpm_exporter:9253
