global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets:
            - localhost:9093
      tls_config:
        insecure_skip_verify: true

rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'php_fpm_exporter'
    static_configs:
      - targets: ['php_fpm_exporter:9253']